game_library/urls.py
"""
URL configuration for game_library project.

The `urlpatterns` list routes URLs to views_dir. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views_dir
    1. Add an import:  from my_app import views_dir
    2. Add a URL to urlpatterns:  path('', views_dir.home, name='home')
Class-based views_dir
    1. Add an import:  from other_app.views_dir import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from library import views
from library.views_dir.crud_views import game, genre, gamegenre, gdp, publisher, developer, profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/profile/<int:pk>', profile.ProfileView.as_view(), name='profile'),
    path('accounts/myprofile', profile.my_profile, name='my-profile'),
    path('accounts/profile/update/email', profile.ProfileEmailUpdateView.as_view(), name='profile-email-update'),
    path('accounts/profile/update/display', profile.ProfileDisplayUpdateView.as_view(), name='profile-display-update'),
    path('accounts/profile/update/avatar', profile.ProfileAvatarUpdateView.as_view(), name='profile-avatar-update'),
    path('accounts/profile/delete/avatar', profile.delete_avatar, name='profile-avatar-delete'),
    path('accounts/profile/<int:pk>/addfriend', profile.request_friendship, name='profile-add-friend'),
    path('accounts/register/', views.RegisterCreateView.as_view(), name='register'),
    path('accounts/logout/', views.CustomLogoutView.as_view(), name='logout'),
    path('manage/admin', views.AdminPanel.as_view(), name='admin-panel'),
    path('accounts/wishlist', views.wishlist, name='wish-list'),
    path('manage/admin/apigames', views.pull_games_from_api, name='update-api-games'),
    path('test', views.test),
    path('', views.Home.as_view(), name='home'),
    path('about', views.About.as_view(), name='about'),
    path('accounts/reviews', views.reviews, name='my-reviews'),
    # -- CART --
    path('cart', views.cart_detail, name='cart'),
    path('cart/add/<int:game_id>', views.cart_add, name='cart-add'),
    path('cart/remove/<int:game_id>', views.cart_remove, name='cart-remove'),
    path('cart/purchase', views.cart_purchase, name='cart-purchase'),
    # -- GAME --
    path('manage/game/create', game.GameCreateView.as_view(), name='game-create'),
    path('manage/game/update/<pk>', game.GameUpdateView.as_view(), name='game-update'),
    path('manage/game/delete/<pk>', game.GameDeleteView.as_view(), name='game-delete'),
    path('view/game', game.GamesTableView.as_view(), name='game-read'),
    path('view/apigame', game.GamesAPITableView.as_view(), name='game-api-read'),
    path('view/apigame/<steamid>', game.GameAPIDetailView.as_view(), name='game-api-read-detail'),
    path('view/game/<int:pk>', game.GameDetailView.as_view(), name='game-read-detail'),
    path('view/game/<int:pk>/addreview', views.ReviewCreateView.as_view(), name='game-add-review'),
    path('view/game/<int:pk>/deletereview', views.ReviewDeleteView.as_view(), name='game-delete-review'),
    # -- GENRE --
    path('manage/genre/create', genre.GenreCreateView.as_view(), name='genre-create'),
    path('manage/genre/update/<pk>', genre.GenreUpdateView.as_view(), name='genre-update'),
    path('manage/genre/delete/<pk>', genre.GenreDeleteView.as_view(), name='genre-delete'),
    # -- GAME_GENRE --
    path('manage/gamegenre/create', gamegenre.GameGenreCreateView.as_view(), name='gamegenre-create'),
    path('manage/gamegenre/update/<pk>', gamegenre.GameGenreUpdateView.as_view(), name='gamegenre-update'),
    path('manage/gamegenre/delete/<pk>', gamegenre.GameGenreDeleteView.as_view(), name='gamegenre-delete'),
    # -- DEVELOPER --
    path('manage/developer/create', developer.DeveloperCreateView.as_view(), name='developer-create'),
    path('manage/developer/update/<pk>', developer.DeveloperUpdateView.as_view(), name='developer-update'),
    path('manage/developer/delete/<pk>', developer.DeveloperDeleteView.as_view(), name='developer-delete'),
    # -- PUBLISHER
    path('manage/publisher/create', publisher.PublisherCreateView.as_view(), name='publisher-create'),
    path('manage/publisher/update/<pk>', publisher.PublisherUpdateView.as_view(), name='publisher-update'),
    path('manage/publisher/delete/<pk>', publisher.PublisherDeleteView.as_view(), name='publisher-delete'),
    # -- GAME_PUBLISHER --
    path('manage/gamepublisher/create', gdp.GamePublisherCreateView.as_view(), name='gamepublisher-create'),
    path('manage/gamepublisher/update/<pk>', gdp.GamePublisherUpdateView.as_view(), name='gamepublisher-update'),
    path('manage/gamepublisher/delete/<pk>', gdp.GamePublisherDeleteView.as_view(), name='gamepublisher-delete'),
    # -- GAME_DEVELOPER --
    path('manage/gamedeveloper/create', gdp.GameDeveloperCreateView.as_view(), name='gamedeveloper-create'),
    path('manage/gamedeveloper/update/<pk>', gdp.GameDeveloperUpdateView.as_view(), name='gamedeveloper-update'),
    path('manage/gamedeveloper/delete/<pk>', gdp.GameDeveloperDeleteView.as_view(), name='gamedeveloper-delete'),
]

library/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# Create your models here.


class UserExtraProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=35, unique=True, validators=[MinLengthValidator(3)])
    owned_games = models.ManyToManyField('Game', through='UserOwnedGames', blank=True, related_name='owned')
    wish_list = models.ManyToManyField('Game', through='UserWishlist', blank=True, related_name='wished')
    avatar = models.ImageField(upload_to='library/static/avatars/', default=None, null=True, blank=True)
    friends = models.ManyToManyField('self', blank=True, related_name='friends')

    def add_friend(self, target):
        if target not in self.friends.all():
            self.friends.add(target)
            self.save()

    def remove_friend(self, target):
        if target in self.friends.all():
            self.friends.remove(target)
            self.save()

    def unfriend(self, target):
        # removing friend from self list
        remover_friend_list = self
        remover_friend_list.remove_friend(target)
        # removing friend from target list
        target_friend_list = UserExtraProfile.objects.get(display_name=target)
        target_friend_list.remove_friend(self)
        self.save()

    def is_mutual(self, target):
        return target in self.friends.all()

    def __str__(self):
        return f'{self.display_name}'


class Game(models.Model):
    title = models.CharField(max_length=220)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    genre = models.ManyToManyField('Genre', through='GameGenre')
    developer = models.ManyToManyField('Developer', through='GameDeveloper')
    publisher = models.ManyToManyField('Publisher', through='GamePublisher')
    release = models.DateField()
    logo = models.ImageField(upload_to='library/static/game/logo/', default=None, null=True, blank=True)
    avatar = models.ImageField(upload_to='library/static/game/avatar/', default=None, null=True, blank=True)

    def __str__(self):
        return f'Game({self.title})'


class Genre(models.Model):
    name = models.CharField(max_length=64)

    def __str__(self):
        return f'Genre({self.name})'


class GameGenre(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

    def __str__(self):
        return f'GameGenre({self.game} & {self.genre})'


class Developer(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return f'Developer({self.name})'


class Publisher(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return f'Publisher({self.name})'


class GameDeveloper(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)

    def __str__(self):
        return f'GDP({self.game} & {self.developer})'


class GamePublisher(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)

    def __str__(self):
        return f'GDP({self.game} & {self.publisher})'


class UserOwnedGames(models.Model):
    user = models.ForeignKey(UserExtraProfile, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    acquire_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'game')

class UserWishlist(models.Model):
    user = models.ForeignKey(UserExtraProfile, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    acquire_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'game')


class FriendRequest(models.Model):
    sender = models.ForeignKey(UserExtraProfile, on_delete=models.CASCADE, related_name='sender')
    receiver = models.ForeignKey(UserExtraProfile, on_delete=models.CASCADE, related_name='receiver')
    is_active = models.BooleanField(blank=True, null=False, default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.sender.display_name

    def accept(self):
        if self.receiver:
            self.receiver.add_friend(self.sender)
            if self.sender:
                self.sender.add_friend(self.receiver)
                self.is_active = False
                self.save()

    def decline(self):
        # receiver declining
        self.is_active = False
        self.save()

    def cancel(self):
        # sender cancels request
        self.is_active = False
        self.save()


class Review(models.Model):
    user = models.ForeignKey(UserExtraProfile, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    is_positive = models.BooleanField()
    review_content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('user', 'game')


class GameFromAPI(models.Model):
    title = models.CharField(max_length=220)
    steamid = models.CharField(max_length=128)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    genre = models.CharField(max_length=128, null=True, blank=True)
    developer = models.CharField(max_length=128, null=True, blank=True)
    publisher = models.CharField(max_length=128, null=True, blank=True)
    release = models.CharField(max_length=128, null=True, blank=True)
    logo = models.CharField(max_length=300, null=True, blank=True)

templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% load static %}
{% block about %}active{% endblock %}

{% block content %}
    <div class="border border-secondary rounded">
        <h1 class="text-center p-3">About</h1>
        <div class="border-top border-secondary mx-3"></div>
        <h3 class="text-center p-3">About page goes here</h3>
        <h3 class="text-center p-3">About page goes here</h3>
        <h3 class="text-center p-3">About page goes here</h3>
        <h3 class="text-center p-3">About page goes here</h3>
    </div>
{% endblock %}

templates/adminpanel.html
{% extends 'base.html' %}
{% block title %}Admin Panel{% endblock %}
{% load static %}
{% block extra_css %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static '/css/dm.css' %}"/>
{% endblock %}
{% block content %}
    <div class="p-3">
        <div id="games" class="flex-fill text-center py-3">
            <div class="d-flex justify-content-between mx-5">
                <h3>GAMES</h3>
                <a href="{% url 'game-create' %}">
                    <button type="button" class="btn btn-success">Add New</button>
                </a>
            </div>
            <div class="border border-secondary p-3 my-3 mx-3" style="height: 400px; overflow-y: scroll">
                <div class="bg-dark mt-3 p-3">
                    <div class="w-25 d-flex align-items-center pt-3">
                        <input class="form-control bg-dark text-white ms-3" id="myInput-games" type="text"
                               placeholder="Search..">
                    </div>
                </div>

                <table id='table-games'
                       data-toggle="table"
                       data-search="true"
                       data-filter-control="true"
                       class="table table-dark table-hover">
                    <thead>
                    <tr>
                        <th scope="col">Title</th>
                        <th scope="col">Genre</th>
                        <th scope="col">Price</th>
                        <th scope="col">Release Date</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    <tbody id="myTable-games">
                    {% for game in games %}
                        <tr style="transform: rotate(0);">
                            <td style="vertical-align: middle">
                                <a href="{% url 'game-read-detail' game.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    {{ game.title }}
                                </a>
                            </td>
                            <td style="vertical-align: middle">
                                {% for genre in game.genre.all %}
                                    {% if game.genre.last == genre %}
                                        {{ genre.name }}
                                    {% else %}
                                        {{ genre.name }},
                                    {% endif %}
                                {% endfor %}
                            </td>
                            <td style="vertical-align: middle">{{ game.price }}</td>
                            <td style="vertical-align: middle">{{ game.release|date }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'game-update' game.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Edit
                                </a>
                                <a href="{% url 'game-delete' game.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Remove
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                    <tfoot>
                    <tr>
                        <td colspan="5" class="p-4"></td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div id="genres" class="flex-fill text-center py-3">
            <div class="flex-fill text-center py-3">
                <div class="d-flex justify-content-between mx-5">
                    <h3>GENRES</h3>
                    <a href="{% url 'genre-create' %}">
                        <button type="button" class="btn btn-success">Add New</button>
                    </a>
                </div>
                <div class="border border-secondary p-3 my-3 mx-3" style="height: 400px; overflow-y: scroll">
                    <div class="bg-dark mt-3 p-3">
                        <div class="w-25 d-flex align-items-center pt-3">
                            <input class="form-control bg-dark text-white ms-3" id="myInput-genres" type="text"
                                   placeholder="Search..">
                        </div>
                    </div>

                    <table id='table-genres'
                           data-toggle="table"
                           data-search="true"
                           data-filter-control="true"
                           class="table table-dark table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody id="myTable-genres">
                        {% for genre in genres %}
                            <td style="vertical-align: middle">{{ genre.name }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'genre-update' genre.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Edit
                                </a>
                                <a href="{% url 'genre-delete' genre.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Remove
                                </a>
                            </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5" class="p-4"></td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div id="developers" class="flex-fill text-center py-3">
            <div class="flex-fill text-center py-3">
                <div class="d-flex justify-content-between mx-5">
                    <h3>DEVELOPERS</h3>
                    <a href="{% url 'developer-create' %}">
                        <button type="button" class="btn btn-success">Add New</button>
                    </a>
                </div>
                <div class="border border-secondary p-3 my-3 mx-3" style="height: 400px; overflow-y: scroll">
                    <div class="bg-dark mt-3 p-3">
                        <div class="w-25 d-flex align-items-center pt-3">
                            <input class="form-control bg-dark text-white ms-3" id="myInput-developers" type="text"
                                   placeholder="Search..">
                        </div>
                    </div>

                    <table id='table-developers'
                           data-toggle="table"
                           data-search="true"
                           data-filter-control="true"
                           class="table table-dark table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody id="myTable-developers">
                        {% for developer in developers %}
                            <td style="vertical-align: middle">{{ developer.name }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'developer-update' developer.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Edit
                                </a>
                                <a href="{% url 'developer-delete' developer.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Remove
                                </a>
                            </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5" class="p-4"></td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <div id="publishers" class="flex-fill text-center py-3">
            <div class="flex-fill text-center py-3">
                <div class="d-flex justify-content-between mx-5">
                    <h3>PUBLISHERS</h3>
                    <a href="{% url 'publisher-create' %}">
                        <button type="button" class="btn btn-success">Add New</button>
                    </a>
                </div>
                <div class="border border-secondary p-3 my-3 mx-3" style="height: 400px; overflow-y: scroll">
                    <div class="bg-dark mt-3 p-3">
                        <div class="w-25 d-flex align-items-center pt-3">
                            <input class="form-control bg-dark text-white ms-3" id="myInput-publishers" type="text"
                                   placeholder="Search..">
                        </div>
                    </div>

                    <table id='table-publishers'
                           data-toggle="table"
                           data-search="true"
                           data-filter-control="true"
                           class="table table-dark table-hover">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Action</th>
                        </tr>
                        </thead>
                        <tbody id="myTable-publishers">
                        {% for publisher in publishers %}
                            <td style="vertical-align: middle">{{ publisher.name }}</td>
                            <td style="vertical-align: middle">
                                <a href="{% url 'publisher-update' publisher.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Edit
                                </a>
                                <a href="{% url 'publisher-delete' publisher.id %}"
                                   class="link-light link-offset-2 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover">
                                    Remove
                                </a>
                            </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="5" class="p-4"></td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
        <script>
        $(document).ready(function () {
            $("#myInput-games").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable-games tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        </script>
        <script>
        $(document).ready(function () {
            $("#myInput-genres").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable-genres tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        </script>
        <script>
        $(document).ready(function () {
            $("#myInput-developers").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable-developers tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        </script>
        <script>
        $(document).ready(function () {
            $("#myInput-publishers").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $("#myTable-publishers tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });
        });
        </script>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    {% block extra_css %}{% endblock %}
    <title>{% block title %}BASE{% endblock %}</title>
</head>
<body class="text-light" style="background-color: #323435">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark border-bottom border-secondary" style="height: 5em">
    <div class="container-fluid container w-50">
        <a class="navbar-brand" href="#">LIBAPP</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% block home %}{% endblock %}" aria-current="page"
                       href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block games %}{% endblock %}" href="{% url 'game-read' %}">Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block steam %}{% endblock %}" href="{% url 'game-api-read' %}">STEAM Games</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% block about %}{% endblock %}" href="{% url 'about' %}">About</a>
                </li>
            </ul>
            {% if user.is_authenticated %}
                <ul class="navbar-nav mb-2 mb-lg-0 ">
                    <li>
                        <h3>
                            <a class="nav-link" href="{% url 'cart' %}">🛒</a>
                        </h3>
                    </li>
                    <div class="collapse navbar-collapse" id="navbarNavDarkDropdown">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink"
                                   role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    {{ user_extra }}
                                </a>
                                <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                                    aria-labelledby="navbarDarkDropdownMenuLink">
                                    <li><a class="dropdown-item" href="{% url 'profile' user.id %}">Profile</a></li>
                                    <li><a class="dropdown-item" href="{% url 'wish-list' %}">Wishlist</a></li>
                                    <li><a class="dropdown-item" href="{% url 'my-reviews' %}">Reviews</a></li>
                                    {% if perms.library.add_game %}
                                        <li><a class="dropdown-item" href="{% url 'admin-panel' %}">Admin Panel</a></li>
                                    {% endif %}
                                    <li>
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </ul>
            {% else %}
                <ul class="navbar-nav mb-2 mb-lg-0">
                    <li>
                        <a class="nav-link" href="{% url 'login' %}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                </ul>
            {% endif %}
        </div>
    </div>
</nav>
<div class="border border-secondary container w-50 mt-5 p-3 bg-dark">
    {% block content %}
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/test.html
{% extends 'base.html' %}
{% block title %}Test{% endblock %}
{% block content %}
    <h2>Test</h2>
{% endblock %}